### ISSUE TITLE
Doesn't load the savedata extracted from switch

### ISSUE THREAD

**Issue by TORNADO03** [Amuyea-gbatemp/Persona-5-Strikers-Scramble-Save-Editor#2]
I tried importing the savedata which I exported from switch but it doesn't seem to load any data in it. My main motive was to convert the save file from PC to switch but it just crashes when tried to import the save file from PC.

**Comment by TORNADO03** [comment]
Actually I made a mistake by loading a blank save file. It does read the files from switch but not from pc, so that's still there.

**Comment by Amuyea-gbatemp** [comment]
So it doesn't work when you converted PC save to switch?

I believe that I could add PC Editor if you can send me your PC save with pictures of what in the game. (The better result would be to back up your original save to somewhere safe. Then save the data on all Slot 1-9 and send me that file)

**Comment by Amuyea-gbatemp** [comment]
I just check the save converter tool, PC save are named differently than the switch.

Edit this line, savedata to SAVEDATA.BIN
https://github.com/Amuyea-gbatemp/Persona-5-Strikers-Scramble-Save-Editor/blob/main/Persona%20Strikers/1.0.0/p5strikers_1_0_0.py#L622

Hope it helps!

**Comment by TORNADO03** [comment]
So to answer your question, pc save when converted to switch save does get read from the editor. My issue was because checkpoint created a corrupted save file when i backed up from switch which created a lot of issues. The editor loaded the save fine but when i restored it in switch, it was corrupted. 

I was able to fix everything by wiping out the whole save data from switch and making fresh backup with jksv which was able to read the converted save file. But yeah it would be a good idea if you can add the functionality of conversion natively in the editor if it isn't too much work. I used the save converter created by zarooboogs to do the conversion which might not be too user-friendly method. If you want a backup of my save file to test then I can send you that. Let me know if I can do anything to help! :)

**Comment by TORNADO03** [comment]
Also I did try editing the line you said to the name of pc savedata.bin but it didn't work which I kind of expected since both files are of different sizes. I would assume the pointers will be different inside as well.

This is the error I got when I clicked on Character Name tab I think

Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\persona5strikers_1_0_0_1.py", line 136, in <lambda>
    btn_character.clicked.connect(lambda: self.show_statwindow("Character_1"))
  File "C:\Users\xxx\Downloads\persona5strikers_1_0_0_1.py", line 1294, in show_statwindow
    str(self.readFromPositionName(NamestatOffsets[x], NamestatOffsets[x] + 8, ">LL"))))
  File "C:\Users\xxx\Downloads\persona5strikers_1_0_0_1.py", line 1390, in readFromPositionName
    valueToRead2 = codecs.decode(valueToRead1, "hex").decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 0: invalid continuation byte

**Comment by Amuyea-gbatemp** [comment]
You can send me the PC save file that you converted (preferred to have Slot 1-9 saved to check each)

**Comment by Amuyea-gbatemp** [comment]
I tested with my friend's PC Save and it loads everything fine. Probably the offsets are different from switch and pc

You need to run https://github.com/zarroboogs/p5spc.saveutil#decrypting-or-encrypting-pc-saves
`p5spc.saveutil.exe crypt --input </path/to/SAVEDATA.BIN> --steam <SteamID64>`

**Comment by TORNADO03** [comment]
[save.zip](https://github.com/Amuyea-gbatemp/Persona-5-Strikers-Scramble-Save-Editor/files/6380144/save.zip)

That's what I used to convert. The zip contains both switch and pc versions of the same save. The original one is PC however, I wanted to migrate it to switch which is why i converted them in the first place.

**Comment by Amuyea-gbatemp** [comment]
I see it, you still need to decrypt the PC save then you can convert to switch

**Comment by TORNADO03** [comment]
I already did it, like the save file is working on my switch lol.

**Comment by Amuyea-gbatemp** [comment]
I mean to use decrypt SAVEDATA.BIN which is named SAVEDATA.BIN_crypt for PC if you wanted to edit it. That's why the save editor throws an error when you give encrypted savedata.bin below

> Traceback (most recent call last):
> File "C:\Users\xxx\Downloads\persona5strikers_1_0_0_1.py", line 136, in
> btn_character.clicked.connect(lambda: self.show_statwindow("Character_1"))
> File "C:\Users\xxx\Downloads\persona5strikers_1_0_0_1.py", line 1294, in show_statwindow
> str(self.readFromPositionName(NamestatOffsets[x], NamestatOffsets[x] + 8, ">LL"))))
> File "C:\Users\xxx\Downloads\persona5strikers_1_0_0_1.py", line 1390, in readFromPositionName
> valueToRead2 = codecs.decode(valueToRead1, "hex").decode('utf-8')
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 0: invalid continuation byte

**Comment by TORNADO03** [comment]
You are correct, I was using the encrypted file which was causing the issue, decrypted file is reading fine on the editor.

**Comment by Amuyea-gbatemp** [comment]
No problem :D
Is that all you need to know or have a different issues?

**Comment by TORNADO03** [comment]
Well the original issue I had wasn't really an issue but it became more so to implement a feature that allows users to directly load their pc save files without having to modify a line in the code. But even if you did that I guess they would need to decrypt the save file first anyway. Anyway yeah that's all I had, thanks!

**Comment by Amuyea-gbatemp** [comment]
I found out that you don't have to modify the line to change the name. It works with any file 🤦
